export const ACTIONS = {
	SET_COMPONENT_TYPE: 'SET_COMPONENT_TYPE',
	SET_COMPONENT_VARIANT: 'SET_COMPONENT_VARIANT',
	SET_SIZE: 'SET_SIZE',
	SET_BORDER_RADIUS: 'SET_BORDER_RADIUS',
	TOGGLE_MODIFIER: 'TOGGLE_MODIFIER',
	SET_ADDITIONAL_CLASSES: 'SET_ADDITIONAL_CLASSES',
	TOGGLE_SPECIAL_CLASS: 'TOGGLE_SPECIAL_CLASS',
	SET_PREVIEW_BG: 'SET_PREVIEW_BG',
	SET_COLOR: 'SET_COLOR',
	SET_CUSTOM_COLOR_SETTINGS: 'SET_CUSTOM_COLOR_SETTINGS',
	RESET_SETTINGS: 'RESET_SETTINGS',
	// UPDATE_GENERATED_CLASS は useClassBuilder 内でのみ使用されているため、
	// ここに含めるか、useClassBuilder 内のローカル定数にするか検討できます。
	// HMR の観点からは、外部で不要なら含めなくても問題ありません。
	// ここでは含めておきます。
	UPDATE_GENERATED_CLASS: 'UPDATE_GENERATED_CLASS',
}
